freebsd_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  env:
    CK_VERBOSITY: verbose
    HDFS_TEST_NODE_ADDRESS: localhost
  install_script:
    - uname -a
    - "pkg install -y check cyrus-sasl gcc gmake pkgconf protobuf protobuf-c"
  build_script:
    - uname -a
    - gmake -j$(sysctl -n hw.ncpu) all
  # only run the unit test suite for now, as it doesn't require a live HDFS cluster
  test_script:
    - env CK_RUN_SUITE=unit gmake test

# only_if feature seems to be broken, at least on FreeBSD, or documented
# incorrectly :/.  The environment variable is populated during scripts, but
# does not appear to exist globally in tasks.
#only_if: $CIRRUS_OS == freebsd
