freebsd_task:
  freebsd_instance:
    image: freebsd-12-3-release-amd64
    cpu: 4
    memory: 8GB
  env:
    CK_VERBOSITY: verbose
    HDFS_TEST_NODE_ADDRESS: localhost
    HDFS_TEST_NODE_PORT: 9000
    HDFS_TEST_USER: root
    HADOOP_ROOT_LOGGER: WARN,DRFA # decrease cluster's log level and don't print to console
    JAVA_HOME: /usr/local/openjdk8-jre
    matrix:
      - CC: clang
      - CC: gcc
  install_script:
    - uname -a
    - pkg install -y check cyrus-sasl gmake pkgconf protobuf-c
    - if [ "$CC" = "gcc" ] ; then pkg install -y gcc; fi
    # install Hadoop to spin up the CLI MiniCluster
    - pkg install -y curl openjdk8-jre bash
    # these mounts are required for this implementation of openjdk8
    - mount -t fdescfs fdesc /dev/fd
    - mount -t procfs proc /proc
    # Parse the latest stable Hadoop version then download it
    - HADOOP_TGZ=$(curl https://dlcdn.apache.org/hadoop/common/stable/ |sed -nEe 's/.*href="(hadoop-([0-9]+\.){3}tar\.gz)".*/\1/p')
    - if [ -z "$HADOOP_TGZ" ] ; then echo "Unable to fetch stable Hadoop name"; exit 1; fi
    - HADOOP_VER="${HADOOP_TGZ%.tar.gz}"
    - echo "Fetching latest stable Hadoop version $HADOOP_VER"
    - curl -O "https://dlcdn.apache.org/hadoop/common/stable/$HADOOP_TGZ"
    - tar xzf "$HADOOP_TGZ"
    - mv "$HADOOP_VER" /usr/local/hadoop
  build_script:
    - uname -a
    - gmake -j$(sysctl -n hw.ncpu) all
  test_script:
    - uname -a
    - HADOOP_JUNIT_JAR_PATH=$(find /usr/local/hadoop -name "junit*.jar")
    # There's a bug where the junit jar needs to be explicitly added to the class path for the minicluster to work
    - export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${HADOOP_JUNIT_JAR_PATH}"
    - /usr/local/hadoop/bin/mapred minicluster -nomr -format -nnport $HDFS_TEST_NODE_PORT -datanodes 4 &
    - CLUSTER_PID=$!
    - echo "CLUSTER_PID $CLUSTER_PID"
    - |
      # Wait until the cluster is up by polling the namenode port with netcat
      cnt=0
      while ! nc -vzw 5 localhost $HDFS_TEST_NODE_PORT ; do
        echo "$cnt"
        cnt=$((cnt + 1))
        if [ "$cnt" -gt "5" ] ; then exit 1; fi
      done
      # Wait a bit longer to ensure the rest of the cluster finalized setup
    - sleep 10
    - gmake test
    - kill $CLUSTER_PID

macos_task:
  macos_instance:
    image: monterey-base
  env:
    # The version of libsasl2 that is included with MacOS command line
    # tools has many of its API functions explicitly marked deprecated
    # for some reason
    CFLAGS: -Wno-error=deprecated-declarations
    CK_VERBOSITY: verbose
    HDFS_TEST_NODE_ADDRESS: localhost
    # Spinning up a test HDFS cluster doesn't seem to work well on
    # Cirrus's MacOS VMs, so only run the unit test suite that doesn't
    # require a live cluster
    CK_RUN_SUITE: unit
  install_script:
    - uname -a
    - brew install check pkg-config protobuf-c
  build_script:
    - uname -a
    - make -j$(sysctl -n hw.ncpu) all
  test_script:
    - uname -a
    - make test
