helloworld: helloworld.c
	gcc -Wall $(CFLAGS) -g -I../include -L../src helloworld.c -lhadoofus -lpthread -o helloworld

hl-hello: hl-hello.c
	gcc -Wall $(CFLAGS) -g -I../include -L../src hl-hello.c -lhadoofus -lpthread -o hl-hello

clean:
	rm -f helloworld
